"""Lettering detector — one vision call that asks whether an image has words.

`api/prompts/cover.md` forbids lettering on a cover about as firmly as prose
can, and the image model obeys it only INTERMITTENTLY: a probe on the same
prompt came back clean while the operator's run came back with "a mess" of
glyphs on it (#67). A rule nothing checks is a request, not a constraint, so
this module is the check: `contains_lettering` hands the generated bytes to a
vision model, asks the single question in `api/prompts/lettering.md`, and
turns the one-word answer into a bool.

WHY A VISION CALL AND NOT OCR. `pytesseract`/`easyocr` would add a system
binary or a model weight to the image for a check that runs once per cover,
and both are tuned to TRANSCRIBE document text — they read a scanned page
well and are weakest on exactly the reported failure mode, stylised or
garbled text-shaped scribbles, which `cover.md` already counts as a
violation. A vision model is asked a question ("is there lettering?") rather
than made to read words that may not spell anything, and it needs no new
dependency: `langchain` and the provider clients are already here.

WHAT IT COSTS. The check is free relative to the thing it checks. One
≈1024×1024 PNG is ≈1.3k input tokens and the reply is one word, so on a
cheap vision model the call is ≈$0.0002 against ≈$0.039 for the image call
that produced those bytes — under 0.5% of one image call, and still ≈$0.0015
on a Haiku-class model. The RETRIES are what cost money, which is why the
attempt budget lives with the retry loop in `api/visuals.py`, not here.

Shaped like `api/imagegen.py`: one narrow public function, model read from
config by ROLE (`image_reviewer`, falling back to the cheap `extractor` so an
operator who configures nothing new still gets the check), its own error
types, and NO retry policy of its own — `contains_lettering` makes exactly
one call and raises. Deciding when to call it, and what a failure means for
the run, is `api/visuals.py:_generate_cover`'s job.

`contains_lettering`'s signature takes BYTES AND NOTHING ELSE — no card, no
prompt, no ledger, no claims — for the same structural reason
`api.imageprompt.build_cover_prompt` is shaped the way it is (#27): a future
engineer cannot "help" the detector with context that would let a claim, or
the cover's own subject matter, reach a model that is only supposed to look
at pixels.

Its error types EXTEND `api/imagegen.py`'s taxonomy rather than reshaping it:
`LetteringCheckError` is an `ImageGenError`, so `_generate_cover`'s existing
`except ImageGenError` clause is a sensible landing pad for it. Deliberately,
`LetteringCheckConfigError` does NOT subclass `ImageGenConfigError` — if it
did, an unconfigured detector would be reported as "image backend not
configured" and would skip the cover entirely, which is the opposite of what
#67 asks for: a cover that cannot be checked still ships, carrying a notice.

API keys are read from the environment by the provider client (byo_key) and
are scrubbed out of any message this module raises, matching
`api/imagegen.py`'s and `api/providers.py`'s precedent.
"""

from __future__ import annotations

import base64
import os
import re
from functools import lru_cache
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from api.config_loader import get_model
from api.imagegen import ImageGenError
from api.jsonio import as_text

_PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "lettering.md"

# Model by ROLE, from config, never a literal model id here (CLAUDE.md).
# Optional with a fallback, exactly like `researcher`/`stylist`: an operator
# who configures nothing new still gets the check, on the cheap extractor.
_ROLE = "image_reviewer"
_FALLBACK_ROLE = "extractor"

# The bytes are always PNG here: `api.imagegen.generate_image` verifies the
# PNG signature before returning, so nothing else can reach this module.
_MIME_TYPE = "image/png"

# Below this length a value cannot be a real credential, and scrubbing it
# would corrupt ordinary words in a message instead of protecting anything.
# Mirrors api/imagegen.py's and api/providers.py's _MIN_SECRET_LEN.
_MIN_SECRET_LEN = 8

# Any provider's key, not just Google's: the reviewer role can resolve to
# anthropic/openai/google, so every `*_API_KEY` in the environment is scrubbed
# rather than one hardcoded name.
_KEY_ENV_SUFFIX = "_API_KEY"

# The one-word answers `api/prompts/lettering.md` asks for. Anything else is
# a provider error, never silently read as "clean" — a detector that is not
# understood must not be able to wave a lettered cover through.
_VERDICTS = {"yes": True, "no": False}


class LetteringCheckError(ImageGenError):
    """Base for every failure this detector raises.

    An `ImageGenError` on purpose (#67): `api/visuals.py:_generate_cover`
    already ends its chain with `except ImageGenError` as the landing pad for
    any other/future subclass, so a detector failure degrades to a sensible
    notice rather than falling through to "unexpected error".
    """


class LetteringCheckConfigError(LetteringCheckError):
    """Setup is wrong: no model role resolves, or the client cannot be built.

    NOT an `ImageGenConfigError`, deliberately — that one means "image backend
    not configured" and makes `_generate_cover` skip the cover. An
    unconfigured DETECTOR must keep the cover and add a "was not checked"
    notice instead.
    """


class LetteringCheckProviderError(LetteringCheckError):
    """The call failed, or the reply could not be parsed into yes/no."""


@lru_cache(maxsize=1)
def _prompt() -> str:
    return _PROMPT_PATH.read_text(encoding="utf-8")


def _scrub(text: str) -> str:
    """Remove any provider API key from `text` before it is raised or logged."""
    for name, value in os.environ.items():
        if not name.endswith(_KEY_ENV_SUFFIX):
            continue
        if value and len(value) >= _MIN_SECRET_LEN:
            text = text.replace(value, "***")
    return text


def _data_url(image_bytes: bytes) -> str:
    """The image as a base64 data URL, the portable multimodal content shape.

    `{"type": "image_url", "image_url": {"url": "data:..."}}` is understood by
    every provider integration this repo configures (google-genai, anthropic,
    openai), so the detector works whichever model the role resolves to.
    """
    encoded = base64.b64encode(image_bytes).decode("ascii")
    return f"data:{_MIME_TYPE};base64,{encoded}"


def _reply_text(reply: object) -> str:
    """The plain text of a chat reply, whether it is a string or blocks."""
    return as_text(getattr(reply, "content", reply)).strip()


def _parse_verdict(text: str) -> bool:
    """Turn the detector's answer into a bool, or raise.

    Reads the FIRST word only, which is what the prompt asks for ("exactly one
    word"). An answer that is neither `yes` nor `no` — a hedge, a description,
    an empty reply — raises `LetteringCheckProviderError`. It is never read as
    "clean": a detector nobody understood must not be able to pass a lettered
    cover, since "clean" is the verdict that ships an image silently.
    """
    words = re.findall(r"[a-z]+", text.lower())
    verdict = _VERDICTS.get(words[0]) if words else None
    if verdict is None:
        shown = text if len(text) <= 80 else text[:77] + "..."
        raise LetteringCheckProviderError(
            f"detector reply was not yes/no: {shown!r}" if shown
            else "detector returned an empty reply"
        )
    return verdict


def contains_lettering(image_bytes: bytes) -> bool:
    """Whether `image_bytes` contains lettering, per one vision call.

    Args:
        image_bytes: the PNG bytes to look at. Bytes and nothing else — no
            card, no prompt, no claims (see the module docstring for why).

    Returns:
        True when the detector says the image contains words, letters,
        numerals, a logo, a watermark or text-shaped scribbles; False when it
        says it contains none.

    Raises:
        LetteringCheckConfigError: no model resolves for the `image_reviewer`
            role or its `extractor` fallback, or the client could not be
            built. Raised before any call reaches a provider.
        LetteringCheckProviderError: the call failed, or the reply could not
            be parsed into yes/no. An unparseable reply is never treated as
            "clean".

    One call only — this function does not retry. Whether to try again with a
    freshly generated image is `api/visuals.py:_generate_cover`'s decision.
    """
    if not image_bytes:
        raise LetteringCheckProviderError("no image bytes to check")

    try:
        model = get_model(_ROLE, temperature=0.0, fallback=_FALLBACK_ROLE)
    except Exception as err:  # unresolved role, unknown provider, missing key
        raise LetteringCheckConfigError(
            _scrub(f"no lettering-detection model configured: {err}")
        ) from err

    messages = [
        SystemMessage(content=_prompt()),
        HumanMessage(
            content=[
                {"type": "text", "text": "Does this image contain any lettering?"},
                {"type": "image_url", "image_url": {"url": _data_url(image_bytes)}},
            ]
        ),
    ]

    try:
        reply = model.invoke(messages)
    except Exception as err:  # network error, API error, SDK-internal failure
        raise LetteringCheckProviderError(
            _scrub(f"lettering check call failed: {err}")
        ) from err

    return _parse_verdict(_scrub(_reply_text(reply)))


__all__ = [
    "LetteringCheckError",
    "LetteringCheckConfigError",
    "LetteringCheckProviderError",
    "contains_lettering",
]
